"""new schema

Revision ID: 18068fbd9df2
Revises: dc3d551be620
Create Date: 2020-01-25 23:11:24.923737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18068fbd9df2'
down_revision = 'dc3d551be620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('user')
    op.drop_table('season')
    op.drop_table('characters')
    op.drop_table('tournament')
    op.drop_table('game')
    op.drop_table('match')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('season_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('witness_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('plus_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minus_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loser_rounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winner_rounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['score.id'], name='match_loser_id_fkey'),
    sa.ForeignKeyConstraint(['season_number'], ['season.number'], name='match_season_number_fkey'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name='match_tournament_id_fkey'),
    sa.ForeignKeyConstraint(['winner_id'], ['score.id'], name='match_winner_id_fkey'),
    sa.ForeignKeyConstraint(['witness_name'], ['user.id'], name='match_witness_name_fkey'),
    sa.PrimaryKeyConstraint('id', name='match_pkey')
    )
    op.create_table('game',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=48), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('img', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='game_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tournament',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('img', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.number'], name='tournament_season_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tournament_pkey')
    )
    op.create_table('characters',
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('sm_img_url', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('lg_img_url', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='characters_pkey')
    )
    op.create_table('season',
    sa.Column('number', sa.INTEGER(), server_default=sa.text("nextval('season_number_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='season_game_id_fkey'),
    sa.PrimaryKeyConstraint('number', name='season_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('witness', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('host', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('score',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_username', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('season_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_username'], ['user.id'], name='score_player_username_fkey'),
    sa.ForeignKeyConstraint(['season_number'], ['season.number'], name='score_season_number_fkey'),
    sa.PrimaryKeyConstraint('id', name='score_pkey')
    )
    # ### end Alembic commands ###
