"""empty message

Revision ID: 68fe17e010b8
Revises: 
Create Date: 2019-02-27 19:08:19.991658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fe17e010b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('player',
    sa.Column('uid', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('witness', sa.Boolean(), nullable=True),
    sa.Column('main_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['main_name'], ['main.name'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('winner_uid', sa.String(length=10), nullable=True),
    sa.Column('loser_uid', sa.String(length=10), nullable=True),
    sa.Column('witness_uid', sa.String(length=10), nullable=True),
    sa.Column('winner_score', sa.Integer(), nullable=False),
    sa.Column('loser_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loser_uid'], ['player.uid'], ),
    sa.ForeignKeyConstraint(['winner_uid'], ['player.uid'], ),
    sa.ForeignKeyConstraint(['witness_uid'], ['player.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('player')
    op.drop_table('main')
    # ### end Alembic commands ###
