"""v2

Revision ID: 9c7eb007004d
Revises: 9d23998df3b8
Create Date: 2020-01-26 00:12:42.395273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7eb007004d'
down_revision = '9d23998df3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('game', sa.Integer(), nullable=False),
    sa.Column('favicon', sa.String(length=256), nullable=False),
    sa.Column('img', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('img', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('slack_id', sa.String(length=10), nullable=True),
    sa.Column('twitch_id', sa.String(length=100), nullable=True),
    sa.Column('twitter_id', sa.String(length=15), nullable=True),
    sa.Column('profile_img', sa.String(length=256), nullable=False),
    sa.Column('homepage', sa.Integer(), nullable=True),
    sa.Column('witness', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('main_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['main_name'], ['characters.name'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('loser_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('winner_wins', sa.Integer(), nullable=False),
    sa.Column('loser_wins', sa.Integer(), nullable=False),
    sa.Column('winner_prev_score', sa.Integer(), nullable=False),
    sa.Column('loser_prev_score', sa.Integer(), nullable=False),
    sa.Column('witness_username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['loser_id'], ['scores.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['scores.id'], ),
    sa.ForeignKeyConstraint(['witness_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('scores')
    op.drop_table('seasons')
    op.drop_table('users')
    op.drop_table('games')
    op.drop_table('characters')
    # ### end Alembic commands ###
