"""v2

Revision ID: bef1e189f492
Revises: 83580498aee4
Create Date: 2020-01-25 23:53:12.328492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef1e189f492'
down_revision = '83580498aee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('matches_loser_username_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_winner_username_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_season_id_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'scores', ['winner_username'], ['username'])
    op.create_foreign_key(None, 'matches', 'scores', ['season_id'], ['season_id'])
    op.create_foreign_key(None, 'matches', 'scores', ['loser_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_season_id_fkey', 'matches', 'seasons', ['season_id'], ['id'])
    op.create_foreign_key('matches_winner_username_fkey', 'matches', 'users', ['winner_username'], ['username'])
    op.create_foreign_key('matches_loser_username_fkey', 'matches', 'users', ['loser_username'], ['username'])
    # ### end Alembic commands ###
