"""empty message

Revision ID: dc3d551be620
Revises: fa3b52d40b5d
Create Date: 2019-10-28 17:59:08.695017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3d551be620'
down_revision = 'fa3b52d40b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('loser_rounds', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('winner_rounds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'winner_rounds')
    op.drop_column('match', 'loser_rounds')
    # ### end Alembic commands ###
