"""empty message

Revision ID: fa3b52d40b5d
Revises: 68fe17e010b8
Create Date: 2019-10-15 00:56:22.642440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3b52d40b5d'
down_revision = '68fe17e010b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('img', sa.String(length=128), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('match', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match', 'tournament', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'tournament_id')
    op.drop_table('tournament')
    # ### end Alembic commands ###
